version: "3"
services:
  redis:
    container_name: customfields-redis
    image: "redis:alpine"
    restart: always
    ports:
      - "6379:6379"
    networks:
      - backend
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 45s
      interval: 10s
      retries: 10
  app:
    container_name: node-redis2
    restart: always
    build: ./
    ports:
      - "80:3000"
    volumes:
      - .:/app
    networks:
      - backend
    links:
      - redis
    depends_on:
      redis:
        condition: service_healthy
networks:
  backend:
    driver: bridge
volumes:
  dbdata:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/srv/redis"
